spring:
  application:
    name: statement-analysis_springboot
  servlet:
    multipart:
      max-file-size: 5MB

aws:
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}
    client-id: ${COGNITO_CLIENT_ID}
    client-secret: ${COGNITO_CLIENT_SECRET}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  sns:
    topic: ${AWS_SNS_TOPIC}
    role: ${AWS_SNS_ROLE}
  kms:
    key-id: ${AWS_KMS_KEY_ALIAS}
logging:
  structured:
    format:
      console: ecs